///<reference path="../js-languative/languative.ts"/>
languative.modifyDictionary("html", {
    pointOfContact: "Point of conctact",
    resourceProvider: "Resource provider",
    publisher: "Publisher",
    author: "Author",
    dateStamp: "Date stamp",
    referenceSystemInfo: "Spatial reference systems: ",
    descriptiveKeywords: "Descriptive keywords",
    resourceConstraints: "Resource constraints",
    accessConstraints: "Access constraints",
    useLimitation: "Use limitations",
    otherConstraints: "otherConstraints",
    otherRestrictions: "Other restrictions",
    spatialRepresentation: "Spatial representation",
    spatialInfo: "Spatial information",
    spatialResolution: "Spatial resolution",
    language: "Language",
    topicCategory: "Topic category",
    metadataId: "Metadata Id",
    topicCategory_boundaries: "Administrative and Political Boundaries",
    topicCategory_farming: "Agriculture and Farming",
    topicCategory_climatologyMeteorologyAtmosphere: "Atmosphere and Climatic",
    topicCategory_biota: "Biology and Ecology",
    topicCategory_economy: "Business and Economic",
    topicCategory_planningCadastre: "Cadastral",
    topicCategory_society: "Cultural, Society and Demography",
    topicCategory_elevation: "Elevation and Derived Products",
    topicCategory_environment: "Environment and Conservation",
    topicCategory_structure: "Facilities and Structures",
    topicCategory_geoscientificInformation: "Geological and Geophysical",
    topicCategory_health: "Human Health and Disease",
    topicCategory_imageryBaseMapsEarthCover: "Imagery and Base Maps",
    topicCategory_inlandWaters: "Inland Water Resources",
    topicCategory_location: "Locations and Geodetic Networks",
    topicCategory_intelligenceMilitary: "Military",
    topicCategory_oceans: "Oceans and Estuaries",
    topicCategory_transportation: "Transportation Networks",
    topicCategory_utilitiesCommunication: "Utilities and Communication",
    language_ger: "German",
    language_dut: "Dutch",
    language_eng: "English",
    language_fre: "French",
    language_ita: "Italian",
    language_kor: "Korean",
    language_lit: "Lithuanian",
    language_nor: "Norwegian",
    language_pol: "Polish",
    language_por: "Portuguese",
    language_rus: "Russian",
    language_spa: "Spanish",
    language_swe: "Swedish",
    language_tur: "Turkish",
    language_chi: "Chinese",
    language_bul: "Bulgarian",
    language_cze: "Czech",
    language_dan: "Danish",
    language_est: "Estonian",
    language_fin: "Finnish",
    language_gre: "Greek",
    language_hun: "Hungarian",
    language_gle: "Irish",
    language_lav: "Latvian",
    language_mlt: "Maltese",
    language_rum: "Romanian",
    language_slo: "Slovak",
    language_slv: "Slovenian",
    spatialRepresentation_vector: "Vector",
    spatialRepresentation_grid: "Grid",
    spatialRepresentation_textTable: "Text Table",
    spatialRepresentation_tin: "TIN",
    spatialRepresentation_stereoModel: "Stereo Model",
    spatialRepresentation_video: "Video",
    distributionFormat: "Distribution format",
    onLineTransfer: "Online transfer",
    onLineTransfer_download: "Download",
    onLineTransfer_information: "Information",
    onLineTransfer_offlineAccess: "Offline Access",
    onLineTransfer_order: "Order",
    onLineTransfer_search: "Search",
    onLineTransfer_undefined: "On-line",
    qualityScope: "Scope",
    lineageStatement: "Lineage statement",
    dataQuality: "Data quality",
    conformancePass: "Pass",
    otherKeywords: "Other keywords",
    type: "Type",
    metadataSchema: "Metadata schema",
    isoMetadataSchema: "ISO/INSPIRE",
    cswMetadataSchema: "OGC Catalogue Service for the Web (CSW)"
});

languative.modifyDictionary("pl", {
    yes: "tak",
    no: "nie",
    Browse: "Przeglądaj",
    "Filter...": "Filtruj...",
    "Details...": "Szczegóły...",
    RecordsShowing: "Pokazuje",
    RecordsOf: "z",
    RecordsSearchResults: "wyników wyszukiwania",
    RequestingDataFromServer: "Pobieranie danych z serwera...",
    Close: "Zamknij",
    Back: "Wróć",
    detailsTitle: "Szczegóły",
    detailsSearch: "Wyszukiwanie",
    detailsOrder: "Zamówienie",
    detailsInfo: "Informacje",
    detailsDownload: "Pobierz",
    Contact: "Kontakt",
    pointOfContact: "Punkt kontaktowy",
    resourceProvider: "Dostawca zasobu",
    publisher: "Wydawca",
    author: "Autor",
    owner: "Właściciel",
    user: "Użytkownik",
    originator: "Twórca",
    distributor: "Dystrybutor",
    processor: "Edytor",
    dateStamp: "Sygnatura czasowa",
    referenceSystemInfo: "Systemy odniesienia przestrzennego",
    Metadata: "Metadane",
    descriptiveKeywords: "Słowa kluczowe",
    resourceConstraints: "Ograniczenia zasobu",
    accessConstraints: "Ograniczenia dostępu",
    useLimitation: "Ograniczenia użytkowania",
    otherConstraints: "Inne ograniczenia",
    otherRestrictions: "Inne restrykcje",
    spatialRepresentation: "Reprezentacja przestrzenna",
    spatialInfo: "Informacja przestrzenna",
    spatialResolution: "Dokładność przestrzenna",
    language: "Język",
    topicCategory: "Kategoria tematyczna",
    metadataId: "Identyfikator",
    "no conditions apply": "brak ograniczeń",
    "conditions unknown": "ograniczenia nieznane",
    Distribution: "Udostępnianie danych",
    distributionFormat: "Format danych",
    onLineTransfer: "Dostęp on-line",
    onLineTransfer_download: "Pobieranie",
    onLineTransfer_information: "Informacje",
    onLineTransfer_offlineAccess: "Dostęp off-line",
    onLineTransfer_order: "Zamówienie",
    onLineTransfer_search: "Wyszukiwanie",
    onLineTransfer_undefined: "On-line",
    qualityScope: "Zakres",
    lineageStatement: "Informacja o zgodności",
    dataQuality: "Jakość danych",
    conformancePass: "Zgodny",
    otherKeywords: "Inne słowa kluczowe",
    type: "Typ",
    metadataSchema: "Schemat metadanych"
});
